development:
  adapter: mysql2
  host: localhost
  database: task_scheduler_development
  encoding: utf8
  username: root
  password: 1234

test: &test
  adapter: mysql2
  host: localhost
  database: task_scheduler_test
  encoding: utf8
  username: root
  password: 1234